./ds_cent datasets/wiki_wcc.txt 1 &> log_wiki &
./ds_cent datasets/skitter_wcc.txt 1 &> log_skitter &
./ds_cent datasets/baidu_wcc.txt 1 &> log_baidu &
./ds_cent datasets/Livejournal_wcc.txt 1 &> log_Livejournal &
./ds_cent datasets/hollywood_wcc.txt 1 &> log_hollywood &
./ds_cent datasets/orkut_wcc.txt 1 &> log_orkut &
./ds_cent datasets/sinaweibo_wcc.txt 1 &> log_sinaweibo &
./ds_cent datasets/webuk_wcc.txt 1 &> log_webuk &
./ds_cent datasets/friendster_wcc.txt 1 &> log_friendster &
