figure(1);
subplot(3,2,1);
plot(baidu(:,2:10)','DisplayName','baidu');
legend('1 tree', '2 tree', '3 tree');
%set(gca, 'YScale', 'log');
subplot(3,2,2);
plot(bio(:,2:10)','DisplayName','bio');
legend('1 tree', '2 tree', '3 tree');
%set(gca, 'YScale', 'log');
subplot(3,2,3);
plot(hollywood(:,2:10)','DisplayName','hollywood');
legend('1 tree', '2 tree', '3 tree');
%set(gca, 'YScale', 'log');
subplot(3,2,4);
plot(livejournal(:,2:10)','DisplayName','livejournal');
legend('1 tree', '2 tree', '3 tree');
%set(gca, 'YScale', 'log');
subplot(3,2,5);
plot(skitter(:,2:10)','DisplayName','skitter');
legend('1 tree', '2 tree', '3 tree');
%set(gca, 'YScale', 'log');
subplot(3,2,6);
plot(wiki(:,2:10)','DisplayName','wiki');
legend('1 tree', '2 tree', '3 tree');
%set(gca, 'YScale', 'log');