k_all=x;
h=plot(k_all);
set(gca,'XLim',[0.5 8.5]);
set(gca,'XTick',[1:8]);
% set(gca,'XTickLabel',{'25K'; '50K'; '100K'; '200K'; '400K'; '800K'});
% set(gca, 'YScale', 'log');
% set(gca,'YLim',[1 1000]);
set(gca,'XTickLabel',{'1'; '2'; '3'; '4'; '5'; '10'; '15'; '20'});
% set(gca,'Xlim',[0 10],'XTick',1:1:9,'XTickLabel',{'Gene' 'Google' 'Hollywood' 'Skitter' 'Baidu' 'Wiki' 'Facebook' 'Livejournal' 'Friendster'});
% text((1:9)-(0.25),ones(1,9)*(-3.5),{'43K' '856K' '1.1M' '1.7M' '2.1M' '2.4M' '3.1M' '4.8M' '65M'},'Fontname', 'Times New Roman', 'Fontsize', 11);
% text(2,-0.0035,'{}','Fontname', 'Times New Roman', 'Fontsize', 11);
% text(3,-0.0035,,'Fontname', 'Times New Roman', 'Fontsize', 11);
% text(4,-0.0035,'{}','Fontname', 'Times New Roman', 'Fontsize', 11);
% text(5,-0.0035,'{}','Fontname', 'Times New Roman', 'Fontsize', 11);
% text(6,-0.0035,'{}','Fontname', 'Times New Roman', 'Fontsize', 11);
% text(7,-0.0035,'{}','Fontname', 'Times New Roman', 'Fontsize', 11);
% text(8,-0.0035,'{}','Fontname', 'Times New Roman', 'Fontsize', 11);
% text(9,-0.0035,'{}','Fontname', 'Times New Roman', 'Fontsize', 11);
set(gca, 'Fontname', 'Times New Roman', 'Fontsize', 15);
ylabel_hand=ylabel('Searching time [\mus]');
set(ylabel_hand,'Fontname', 'Times New Roman', 'Fontsize', 15);
xlabel_hand=xlabel('Number of machines');
set(ylabel_hand,'Fontname', 'Times New Roman', 'Fontsize', 15);
legend_str= {'Google'; 'Wiki'; 'Skitter'; 'Gene'; 'Baidu'; 'Facebook'; 'Livejournal'; 'Hollywood'};
legend_hand = columnlegend(2, legend_str, 'Location', 'northeast');
set(legend_hand,'Fontname', 'Times New Roman', 'Fontsize', 11);